%{
EGR102 HEADER COMMENT
Authors:    Alessandra Lozano , ID#12523364
Assignment: EGR 102- Play A Song
Due Date:  December 12 2022
Purpose:   Plays Don't Rain On My Parade
  
%}

%%% Arduino configuration: change these lines as necessary
clear
a = arduino();

%%% Your program goes here. Variable a is your Arduino object.

% Frequencies of musical notes, in Hz.
D4 = 294;
C4 = 262;
F4 = 349;
E4 = 330;
G4 =392;

Rest = 0;

% Durations of musical notes, in seconds.
Whole = 0.6;
Half = Whole / 2;
Quarter = Whole / 4;
Eight = Whole/8;

% The song to play.  Column 1 is the note, column 2 the duration. 
Song = [ G4/2,     Quarter; ...
         G4/2,     Eight; ...
         E4/2,     Quarter;...
         G4/2,     Quarter;...
         G4/2,     Quarter; ...
         Rest,   Quarter;...
         C4/2,     Quarter; ...
         G4/2,     Eight;...
         F4/2,     Quarter;...
         E4/2,     Quarter;...
         D4/4,     Eight;... %Dividing by 2 goes an octave lower
         Rest,   Quarter;...
          G4/2,     Quarter; ...
         G4/2,     Eight; ...
         E4/2,     Quarter;...
         G4/2,     Quarter;...
         G4/2,     Quarter; ...
         Rest,   Quarter;...
         C4/2,     Quarter; ...
         G4/2,     Eight;...
         F4/2,     Quarter;...
         E4/2,     Quarter;...
         D4/4,     Eight;... 
         Rest,   Quarter;...
         % Multiplying by two goes up an octave
       ];
%Divided all by 2 in order to make all my notes an octave lower to match
%more with Dont Rain On My Parade 

while true
    if readDigitalPin(a, 'D2')
        for idx = 1 : length(Song) % number of rows
            playTone(a, 'D9', Song(idx, 1), Song(idx, 2));
            % Wait until the note is over before starting the next one.
            pause(Song(idx, 2));
        end
    end
end





